name: bmi_calculator
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.7.0
  sqflite: ^1.0.0
  path_provider: ^0.4.1
  moor_flutter: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^2.4.0
  build_runner: ^1.8.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/cover.jpg
